# -*- coding: utf-8 -*-
"""فهرست ماهواره‌های شاخص: از هر مدار، مهم‌ترین‌ها با کاربردهای گوناگون."""
import json, re, sys

# (norad_id, fa, en, use, op, wiki_title, fa_desc, en_desc)
T = [
# ---------------- ایستگاه‌ها و فضاپیماهای سرنشین‌دار ----------------
(25544,"ایستگاه فضایی بین‌المللی","International Space Station","station","nasa","International Space Station",
 "بزرگ‌ترین سازهٔ ساخت بشر در مدار با جرم حدود ۴۲۰ تن؛ از سال ۲۰۰۰ پیوسته سرنشین دارد و هر ۹۰ دقیقه یک بار زمین را دور می‌زند.",
 "The largest human-made structure in orbit, permanently crewed since 2000 and circling Earth every 90 minutes."),
(48274,"پیمانهٔ اصلی تیان‌هه","Tianhe core module","station","cnsa","Tianhe core module",
 "هستهٔ ایستگاه فضایی چین که بخش زیستگاه و کنترل ایستگاه را در بر دارد.",
 "Core module of China's space station, housing living quarters and station control."),
(53239,"پیمانهٔ آزمایشگاهی ون‌تیان","Wentian laboratory module","station","cnsa","Wentian",
 "نخستین پیمانهٔ آزمایشگاهی ایستگاه چین، ویژهٔ پژوهش‌های زیست‌شناسی و پیاده‌روی فضایی.",
 "China's first station laboratory module, for biology research and EVA support."),
(54216,"پیمانهٔ آزمایشگاهی مِنگ‌تیان","Mengtian laboratory module","station","cnsa","Mengtian",
 "پیمانهٔ آزمایشگاهی دوم ایستگاه چین با کوره‌ها و آزمایشگاه‌های ریزگرانشی.",
 "Second laboratory module of China's station, with microgravity science racks."),
(67796,"فضاپیمای کرو دراگون","Crew Dragon","station","spacex","SpaceX Dragon 2",
 "کپسول سرنشین‌دار شرکت خصوصی که خدمه را به ایستگاه بین‌المللی می‌برد و بازمی‌گرداند.",
 "Commercial crew capsule ferrying astronauts to and from the ISS."),
(68689,"فضاپیمای باری سیگنِس","Cygnus cargo spacecraft","station","nasa","Cygnus (spacecraft)",
 "فضاپیمای باری یک‌بارمصرف که بار و آزمایش‌ها را به ایستگاه بین‌المللی می‌رساند.",
 "Expendable cargo freighter delivering supplies and experiments to the ISS."),
(68837,"فضاپیمای باری پراگرس","Progress cargo spacecraft","station","roscosmos","Progress (spacecraft)",
 "فضاپیمای باری روسی که سوخت، آب و خوراک ایستگاه را تأمین و مدار آن را اصلاح می‌کند.",
 "Russian cargo ship supplying propellant, water and food, and reboosting the station."),
(69049,"فضاپیمای باری تیان‌ژو","Tianzhou cargo spacecraft","station","cnsa","Tianzhou (spacecraft)",
 "فضاپیمای باری چین برای پشتیبانی از ایستگاه تیان‌گونگ.",
 "Chinese cargo spacecraft resupplying the Tiangong station."),
(69180,"فضاپیمای سرنشین‌دار شن‌ژو","Shenzhou crewed spacecraft","station","cnsa","Shenzhou (spacecraft)",
 "کپسول سرنشین‌دار چین که فضانوردان را به ایستگاه تیان‌گونگ می‌برد.",
 "China's crewed capsule carrying taikonauts to the Tiangong station."),

# ---------------- رصدخانه‌های فضایی و اخترفیزیک ----------------
(20580,"تلسکوپ فضایی هابل","Hubble Space Telescope","science","nasa","Hubble Space Telescope",
 "تلسکوپ ۲٫۴ متری در مدار پایین که از ۱۹۹۰ چهرهٔ کیهان‌شناسی نوین را دگرگون کرده است.",
 "A 2.4-metre observatory in low orbit that has reshaped modern cosmology since 1990."),
(25989,"رصدخانهٔ پرتو ایکس ایکس‌ام‌ام-نیوتن","XMM-Newton","science","esa","XMM-Newton",
 "رصدخانهٔ پرتو ایکس اروپا در مداری بسیار کشیده که چاه‌های گرانشی و خوشه‌های کهکشانی را می‌کاود.",
 "ESA's X-ray observatory in a highly elliptical orbit, probing black holes and galaxy clusters."),
(28485,"رصدخانهٔ انفجارهای پرتو گاما سویفت","Neil Gehrels Swift Observatory","science","nasa","Neil Gehrels Swift Observatory",
 "رصدخانه‌ای که در چند ثانیه به سوی انفجارهای پرتو گاما می‌چرخد و سرچشمهٔ آن‌ها را می‌یابد.",
 "Slews within seconds to catch gamma-ray bursts and pinpoint their sources."),
(38358,"تلسکوپ پرتو ایکس سخت نواستار","NuSTAR","science","nasa","NuSTAR",
 "نخستین تلسکوپ متمرکزکنندهٔ پرتو ایکس پرانرژی برای مطالعهٔ سیاه‌چاله‌ها و بازمانده‌های ابرنواختر.",
 "First focusing high-energy X-ray telescope, studying black holes and supernova remnants."),
(43435,"شکارگر سیارات فراخورشیدی تِس","TESS","science","nasa","Transiting Exoplanet Survey Satellite",
 "در مداری بیضوی و همنوا با ماه، درخشش ستارگان نزدیک را می‌پاید تا گذر سیارات را بیابد.",
 "In a lunar-resonant elliptical orbit, it watches nearby stars for planetary transits."),
(49954,"رصدخانهٔ قطبش پرتو ایکس آی‌ایکس‌پی‌ای","IXPE","science","nasa","Imaging X-ray Polarimetry Explorer",
 "نخستین رصدخانه‌ای که قطبش پرتو ایکس اجرام پرانرژی را اندازه می‌گیرد.",
 "The first observatory measuring the X-ray polarisation of high-energy objects."),
(36395,"رصدخانهٔ دینامیک خورشیدی","Solar Dynamics Observatory","science","nasa","Solar Dynamics Observatory",
 "هر ۱۲ ثانیه تصویری کامل از خورشید می‌گیرد و میدان مغناطیسی آن را می‌سنجد.",
 "Images the entire Sun every 12 seconds and maps its magnetic field."),
(29479,"رصدخانهٔ خورشیدی هینودی","Hinode","science","jaxa","Hinode (satellite)",
 "رصدخانهٔ خورشیدی ژاپن با تلسکوپ نوری، پرتو ایکس و طیف‌سنج فرابنفش شدید.",
 "Japan's solar observatory with optical, X-ray and extreme-ultraviolet instruments."),
(41896,"کاوشگر کمربند تابشی آراسه","Arase","science","jaxa","Arase (satellite)",
 "ذرات پرانرژی کمربندهای تابشی زمین را در مداری کشیده اندازه می‌گیرد.",
 "Measures energetic particles of Earth's radiation belts from an elliptical orbit."),
(40482,"منظومهٔ چهارگانهٔ ام‌ام‌اس","Magnetospheric Multiscale","science","nasa","Magnetospheric Multiscale Mission",
 "چهار فضاپیمای هم‌پرواز که پدیدهٔ بازپیوند مغناطیسی را در دم‌ مغناط‌کره می‌کاوند.",
 "Four spacecraft flying in formation to study magnetic reconnection."),
(30580,"کاوشگر شفق تمیس","THEMIS","science","nasa","THEMIS",
 "منظومه‌ای از کاوشگرها برای شناخت زیرتوفان‌های مغناطیسی و شفق قطبی.",
 "A constellation probing magnetic substorms and the auroral process."),

# ---------------- علوم زمین، اقلیم و اقیانوس ----------------
(25994,"ماهوارهٔ ترا","Terra","earthsci","nasa","Terra (satellite)",
 "پرچمدار برنامهٔ رصد زمین ناسا با سنجندهٔ مودیس؛ ابر، آتش‌سوزی و پوشش گیاهی را می‌پاید.",
 "Flagship of NASA's Earth Observing System, mapping clouds, fires and vegetation."),
(27424,"ماهوارهٔ آکوا","Aqua","earthsci","nasa","Aqua (satellite)",
 "چرخهٔ آب زمین را از بخار جو تا رطوبت خاک و یخ دریایی اندازه می‌گیرد.",
 "Tracks Earth's water cycle from vapour to soil moisture and sea ice."),
(28376,"ماهوارهٔ آئورا","Aura","earthsci","nasa","Aura (satellite)",
 "لایهٔ ازن، آلاینده‌های جوی و شیمی هواسپهر را رصد می‌کند.",
 "Monitors the ozone layer, air pollutants and atmospheric chemistry."),
(37849,"ماهوارهٔ سومی‌ان‌پی‌پی","Suomi NPP","weather","noaa","Suomi NPP",
 "پل میان نسل‌های هواشناسی قطبی آمریکا با سنجندهٔ شب‌بین ویرس.",
 "Bridge between US polar weather generations, carrying the VIIRS day-night imager."),
(43013,"نوآ-۲۰","NOAA-20","weather","noaa","NOAA-20",
 "ماهوارهٔ هواشناسی قطبی که داده‌های بنیادی مدل‌های پیش‌بینی جهانی را فراهم می‌کند.",
 "Polar weather satellite feeding the world's numerical forecast models."),
(54234,"نوآ-۲۱","NOAA-21","weather","noaa","NOAA-21",
 "تازه‌ترین ماهوارهٔ قطبی سامانهٔ مشترک قطبی آمریکا.",
 "Latest spacecraft of the US Joint Polar Satellite System."),
(38771,"متآپ-بی","MetOp-B","weather","eumetsat","MetOp",
 "ماهوارهٔ قطبی اروپا که نیم‌رخ دما و رطوبت جو را برای پیش‌بینی هوا می‌سنجد.",
 "Europe's polar weather satellite sounding atmospheric temperature and humidity."),
(43689,"متآپ-سی","MetOp-C","weather","eumetsat","MetOp",
 "سومین ماهوارهٔ نسل نخست متآپ در مدار قطبی صبحگاهی.",
 "Third first-generation MetOp spacecraft in the morning polar orbit."),
(65159,"متآپ نسل دوم","MetOp-SG A1","weather","eumetsat","MetOp-SG",
 "نخستین ماهوارهٔ نسل دوم قطبی اروپا با سنجنده‌های پیشرفتهٔ جوی.",
 "First of Europe's second-generation polar weather satellites."),
(43476,"گریس-فالوآن","GRACE-FO","earthsci","nasa","GRACE-FO",
 "دو ماهوارهٔ همراه که با سنجش فاصلهٔ خود تغییرات میدان گرانش و ذخایر آب زمین را می‌سنجند.",
 "Twin satellites measuring gravity change and water storage by ranging to each other."),
(54754,"ماهوارهٔ آب‌شناسی سوآت","SWOT","earthsci","nasa","Surface Water and Ocean Topography",
 "نخستین ماهواره‌ای که پستی و بلندی همهٔ آب‌های سطحی زمین را با رادار عرض‌سنج نقشه‌برداری می‌کند.",
 "First mission mapping the elevation of all Earth's surface water with radar interferometry."),
(40376,"ماهوارهٔ رطوبت خاک اس‌مپ","SMAP","earthsci","nasa","Soil Moisture Active Passive",
 "رطوبت خاک و یخ‌زدگی سطح زمین را برای کشاورزی و پیش‌بینی خشکسالی می‌سنجد.",
 "Measures soil moisture and freeze-thaw state for agriculture and drought forecasting."),
(41240,"ارتفاع‌سنج اقیانوسی جیسون-۳","Jason-3","earthsci","noaa","Jason-3",
 "تراز جهانی دریا را با دقت چند سانتی‌متر پایش می‌کند.",
 "Monitors global sea level to a few centimetres of accuracy."),
(46984,"سنتینل-۶ مایکل فرایلیش","Sentinel-6 Michael Freilich","earthsci","esa","Sentinel-6 Michael Freilich",
 "جانشین جیسون‌ها و مرجع کنونی اندازه‌گیری بالا آمدن آب دریاها.",
 "Successor to Jason, now the reference mission for sea-level rise."),
(43613,"آیس‌ست-۲","ICESat-2","earthsci","nasa","ICESat-2",
 "با لیزر، ضخامت یخ قطبی و ارتفاع جنگل‌ها را با دقت سانتی‌متری اندازه می‌گیرد.",
 "Laser altimetry of polar ice thickness and forest height at centimetre precision."),
(36508,"کرایوست-۲","CryoSat-2","earthsci","esa","CryoSat-2",
 "ماهوارهٔ یخ‌شناسی اروپا برای سنجش ضخامت یخ دریایی و کلاهک‌های قطبی.",
 "Europe's ice mission measuring sea-ice thickness and polar ice caps."),
(39452,"سوآرم-اِی","Swarm A","earthsci","esa","Swarm (spacecraft)",
 "سه‌گانهٔ اروپایی که میدان مغناطیسی زمین و منشأ آن در هستهٔ سیاره را نقشه‌برداری می‌کند.",
 "European trio mapping Earth's magnetic field and its origin in the planet's core."),
(33492,"گوست (ایبوکی)","GOSAT (Ibuki)","earthsci","jaxa","Greenhouse Gases Observing Satellite",
 "نخستین ماهوارهٔ اختصاصی سنجش گازهای گلخانه‌ای از فضا.",
 "The first satellite dedicated to measuring greenhouse gases from space."),
(43672,"گوست-۲","GOSAT-2","earthsci","jaxa","GOSAT-2",
 "نسل دوم پایش دی‌اکسید کربن و متان جو زمین.",
 "Second-generation monitoring of atmospheric carbon dioxide and methane."),
(38337,"جی‌کام-دبلیو شیزوکو","GCOM-W (Shizuku)","earthsci","jaxa","Global Change Observation Mission",
 "با رادیومتر ریزموج، بخار آب، بارش و یخ دریایی را می‌سنجد.",
 "Microwave radiometry of water vapour, precipitation and sea ice."),
(43065,"جی‌کام-سی شیکیسای","GCOM-C (Shikisai)","earthsci","jaxa","Global Change Observation Mission",
 "رنگ اقیانوس، هواویزها و پوشش گیاهی را برای مطالعهٔ اقلیم رصد می‌کند.",
 "Observes ocean colour, aerosols and vegetation for climate studies."),
(35931,"اوشن‌ست-۲","Oceansat-2","earthsci","isro","Oceansat-2",
 "ماهوارهٔ اقیانوس‌شناسی هند برای سنجش باد سطح دریا و شکوفایی پلانکتون.",
 "India's ocean mission measuring sea-surface wind and plankton blooms."),
(54361,"اوشن‌ست-۳","Oceansat-3","earthsci","isro","Oceansat-3",
 "نسل تازهٔ اقیانوس‌شناسی هند با سنجندهٔ رنگ اقیانوس و طیف‌سنج گرمایی.",
 "India's newest ocean satellite with ocean-colour and thermal instruments."),
(39086,"سارال","SARAL","earthsci","isro","SARAL",
 "همکاری هند و فرانسه برای ارتفاع‌سنجی دقیق اقیانوس‌ها در باند کا.",
 "Indo-French Ka-band radar altimetry of the oceans."),
(43609,"های‌یانگ-۱سی","Haiyang-1C","earthsci","cnsa","Haiyang-1C",
 "ماهوارهٔ رنگ‌سنجی اقیانوس چین برای پایش آلودگی و شیلات.",
 "China's ocean-colour satellite for pollution and fisheries monitoring."),

# ---------------- سنجش از دور نوری ----------------
(39084,"لندست-۸","Landsat 8","eo","nasa","Landsat 8",
 "میراث پنجاه‌سالهٔ پایش تغییرات زمین با تصاویر چندطیفی سی‌متری.",
 "Continues a 50-year record of land change with 30-metre multispectral imagery."),
(49260,"لندست-۹","Landsat 9","eo","nasa","Landsat 9",
 "تازه‌ترین ماهوارهٔ برنامهٔ لندست که هر هشت روز با لندست-۸ زمین را می‌پوشاند.",
 "Newest Landsat, giving 8-day global coverage together with Landsat 8."),
(40697,"سنتینل-۲اِی","Sentinel-2A","eo","esa","Sentinel-2",
 "تصویربردار چندطیفی ده‌متری برنامهٔ کوپرنیک برای کشاورزی و پایش جنگل.",
 "Copernicus 10-metre multispectral imager for agriculture and forest monitoring."),
(42063,"سنتینل-۲بی","Sentinel-2B","eo","esa","Sentinel-2",
 "همزاد سنتینل-۲اِی که بازدید جهانی را به پنج روز می‌رساند.",
 "Twin of Sentinel-2A, bringing global revisit down to five days."),
(41335,"سنتینل-۳اِی","Sentinel-3A","earthsci","esa","Sentinel-3",
 "دمای سطح دریا و خشکی، رنگ اقیانوس و ارتفاع موج را می‌سنجد.",
 "Measures sea and land surface temperature, ocean colour and wave height."),
(42969,"سنتینل-۵پی","Sentinel-5P","earthsci","esa","Sentinel-5 Precursor",
 "نقشه‌بردار روزانهٔ آلاینده‌های جو از دی‌اکسید نیتروژن تا متان.",
 "Daily global mapping of air pollutants from nitrogen dioxide to methane."),
(40115,"وردویو-۳","WorldView-3","eo","maxar","WorldView-3",
 "یکی از دقیق‌ترین تصویربرداران تجاری با تفکیک حدود سی سانتی‌متر.",
 "One of the sharpest commercial imagers, resolving about 30 centimetres."),
(35946,"وردویو-۲","WorldView-2","eo","maxar","WorldView-2",
 "تصویربردار تجاری هشت‌باندی برای نقشه‌برداری شهری و دفاعی.",
 "Eight-band commercial imager for urban mapping and defence."),
(38012,"پلیاد ۱اِی","Pléiades 1A","eo","airbus","Pléiades (satellite)",
 "ماهوارهٔ چابک فرانسوی با تصاویر نیم‌متری و توان تصویربرداری استریو.",
 "Agile French satellite delivering half-metre and stereo imagery."),
(48268,"پلیاد نئو ۳","Pléiades Neo 3","eo","airbus","Pléiades Neo",
 "نسل تازهٔ اروپایی با تفکیک سی سانتی‌متر و بازدید روزانه.",
 "New European generation at 30 centimetres with daily revisit."),
(38755,"اسپات-۶","SPOT 6","eo","airbus","SPOT (satellite)",
 "پوشش گستردهٔ ۶۰ کیلومتری با تفکیک ۱٫۵ متر برای نقشه‌برداری منطقه‌ای.",
 "Wide 60-kilometre swath at 1.5 metres for regional mapping."),
(29268,"آریرانگ-۲","Arirang-2 (KOMPSAT-2)","eo","kari","KOMPSAT-2",
 "ماهوارهٔ تصویربرداری کرهٔ جنوبی با تفکیک یک‌متری.",
 "South Korea's one-metre optical imaging satellite."),
(40536,"کومپ‌ست-۳اِی","KOMPSAT-3A","eo","kari","KOMPSAT-3A",
 "تصویربردار کره‌ای با دوربین مادون قرمز گرمایی و تفکیک نیم‌متری.",
 "Korean imager with a thermal infrared camera and half-metre optics."),
(32783,"کارتوست-۲اِی","Cartosat-2A","eo","isro","Cartosat-2",
 "ماهوارهٔ نقشه‌برداری هند با تصاویر زیرمتری.",
 "India's cartographic satellite with sub-metre imagery."),
(41877,"ریسورس‌ست-۲اِی","Resourcesat-2A","eo","isro","Resourcesat-2A",
 "پایش منابع طبیعی، کشاورزی و کاربری اراضی هند.",
 "Monitors India's natural resources, agriculture and land use."),
(38038,"زیوان ۱-۰۲سی","Ziyuan 1-02C","eo","cnsa","Ziyuan",
 "ماهوارهٔ منابع زمینی چین برای نقشه‌برداری و زمین‌شناسی.",
 "Chinese land-resources satellite for mapping and geology."),
(45939,"زیوان ۳-۰۳","Ziyuan 3-03","eo","cnsa","Ziyuan 3",
 "ماهوارهٔ نقشه‌برداری سه‌بعدی چین با دوربین‌های استریو.",
 "China's stereo-mapping satellite for 3-D topography."),
(47699,"آمازونیا-۱","Amazonia-1","eo","inpe","Amazônia-1",
 "نخستین ماهوارهٔ کاملاً برزیلی برای پایش جنگل‌زدایی در آمازون.",
 "Brazil's first fully domestic satellite, watching deforestation in the Amazon."),
(40336,"سی‌برس-۴","CBERS-4","eo","inpe","China–Brazil Earth Resources Satellite",
 "برنامهٔ مشترک چین و برزیل برای سنجش منابع زمینی.",
 "The China–Brazil Earth Resources Satellite programme."),
(41601,"اسکای‌ست-سی۱","SkySat-C1","eo","planet","SkySat",
 "ماهوارهٔ کوچک تجاری با توان فیلم‌برداری ویدئویی از زمین.",
 "Small commercial satellite able to shoot video of the ground."),
(58271,"فلاک ۴کیو-۱۶ (کبوتر)","Flock 4Q-16 (Dove)","eo","planet","Planet Labs",
 "یکی از صدها ماهوارهٔ کفشی‌شکل که هر روز کل خشکی زمین را تصویربرداری می‌کنند.",
 "One of hundreds of shoebox-sized satellites imaging all land daily."),
(60454,"ای‌اواس-۰۸","EOS-08","tech","isro","EOS-08",
 "ماهوارهٔ کوچک هند با دوربین فروسرخ و بار آزمایشی نو.",
 "India's microsatellite with an infrared camera and technology payloads."),

# ---------------- رادار روزنهٔ ترکیبی ----------------
(39634,"سنتینل-۱اِی","Sentinel-1A","sar","esa","Sentinel-1",
 "رادار باند سی که در شب و ابر هم نشست زمین، نفت‌ریزی و سیل را می‌بیند.",
 "C-band radar that sees subsidence, oil spills and floods through cloud and night."),
(62261,"سنتینل-۱سی","Sentinel-1C","sar","esa","Sentinel-1",
 "جانشین سنتینل-۱بی که پوشش راداری کوپرنیک را کامل کرد.",
 "Replacement for Sentinel-1B, restoring full Copernicus radar coverage."),
(31698,"تراسار-ایکس","TerraSAR-X","sar","dlr","TerraSAR-X",
 "رادار باند ایکس آلمان با تفکیک تا یک متر.",
 "Germany's X-band radar with resolution down to one metre."),
(36605,"تندم-ایکس","TanDEM-X","sar","dlr","TanDEM-X",
 "همراه تراسار-ایکس؛ این دو با هم نخستین نقشهٔ ارتفاعی یکدست جهان را ساختند.",
 "Flies with TerraSAR-X; together they built the first uniform global elevation model."),
(32382,"رادارست-۲","RADARSAT-2","sar","csa","RADARSAT-2",
 "رادار کانادایی برای پایش یخ دریایی و کشتیرانی قطبی.",
 "Canadian radar monitoring sea ice and Arctic shipping."),
(44322,"مأموریت رادار کانادا","RADARSAT Constellation","sar","csa","RADARSAT Constellation Mission",
 "سه‌گانهٔ راداری کانادا با بازدید روزانهٔ قلمرو قطبی.",
 "Canada's radar trio with daily coverage of the Arctic."),
(43215,"پاز","PAZ","sar","hisdesat","Paz (satellite)",
 "رادار اسپانیایی با کاربرد دوگانهٔ نظامی و غیرنظامی.",
 "Spain's dual-use civilian and military radar satellite."),
(43641,"سائوکوم ۱اِی","SAOCOM 1A","sar","conae","SAOCOM",
 "رادار باند اِل آرژانتین برای سنجش رطوبت خاک در عمق.",
 "Argentina's L-band radar measuring soil moisture at depth."),
(39766,"آلوس-۲ (دایچی-۲)","ALOS-2 (Daichi-2)","sar","jaxa","ALOS-2",
 "رادار باند اِل ژاپن برای پایش زلزله، آتشفشان و جنگل.",
 "Japan's L-band radar for earthquakes, volcanoes and forests."),
(60182,"آلوس-۴","ALOS-4","sar","jaxa","ALOS-4",
 "نسل تازهٔ رادار ژاپن با پهنای دید بسیار بیشتر.",
 "Japan's next-generation radar with a much wider observation swath."),
(43800,"آیس‌آی-ایکس۲","ICEYE-X2","sar","iceye","ICEYE",
 "از نخستین رادارهای کوچک تجاری که پایش لحظه‌ای سیل را ممکن کرد.",
 "One of the first small commercial radars, enabling near-real-time flood mapping."),
(57693,"کاپلا-۱۱ (آکادیا-۱)","Capella-11 (Acadia-1)","sar","capella","Capella Space",
 "رادار تجاری آمریکایی با تفکیک نیم‌متری و تحویل سریع تصویر.",
 "US commercial radar delivering half-metre imagery on demand."),

# ---------------- هواشناسی زمین‌ثابت ----------------
(41866,"گوز-۱۶","GOES-16","weather","noaa","GOES-16",
 "دیدبان زمین‌ثابت شرق آمریکا که هر ۳۰ ثانیه از تندبادها تصویر می‌گیرد.",
 "Geostationary sentinel over the US east, imaging hurricanes every 30 seconds."),
(51850,"گوز-۱۸","GOES-18","weather","noaa","GOES-18",
 "دیدبان اقیانوس آرام و غرب آمریکا برای پایش توفان و آتش‌سوزی.",
 "Watches the Pacific and western US for storms and wildfires."),
(60133,"گوز-۱۹","GOES-19","weather","noaa","GOES-19",
 "تازه‌ترین ماهوارهٔ زمین‌ثابت آمریکا با دیدبان تاج خورشید.",
 "Newest US geostationary weather satellite, also watching the solar corona."),
(40732,"متئوست-۱۱","Meteosat-11","weather","eumetsat","Meteosat",
 "دیدبان زمین‌ثابت اروپا و آفریقا از مدار صفر درجه.",
 "Europe and Africa's geostationary weather watch at zero degrees longitude."),
(54743,"متئوست-۱۲ (نسل سوم)","Meteosat-12 (MTG-I1)","weather","eumetsat","Meteosat Third Generation",
 "نسل سوم اروپایی با تصویربردار سریع و نخستین نقشه‌بردار آذرخش قاره‌ای.",
 "Third-generation Europe imager with the first continental lightning mapper."),
(64723,"ام‌تی‌جی-اس۱","MTG-S1","weather","eumetsat","Meteosat Third Generation",
 "نخستین ماهوارهٔ صوت‌سنج زمین‌ثابت اروپا برای نیم‌رخ‌گیری جو.",
 "Europe's first geostationary sounder for vertical atmospheric profiles."),
(41836,"هیماواری-۹","Himawari-9","weather","jma","Himawari 8",
 "دیدبان زمین‌ثابت ژاپن بر فراز آسیای شرقی و اقیانوسیه.",
 "Japan's geostationary watch over East Asia and Oceania."),
(44903,"الکترو-اِل ۳","Elektro-L 3","weather","roscosmos","Elektro-L",
 "ماهوارهٔ هواشناسی زمین‌ثابت روسیه بر فراز اقیانوس هند.",
 "Russia's geostationary weather satellite over the Indian Ocean."),
(41882,"فِنگ‌یون-۴اِی","Fengyun-4A","weather","cma","Fengyun",
 "نسل دوم زمین‌ثابت چین با صوت‌سنج فروسرخ پیشرفته.",
 "China's second-generation geostationary satellite with an infrared sounder."),
(48808,"فِنگ‌یون-۴بی","Fengyun-4B","weather","cma","Fengyun",
 "ماهوارهٔ عملیاتی چین برای پایش پیوستهٔ توفان‌های آسیای شرقی.",
 "China's operational satellite tracking East Asian storms."),
(39216,"اینست-۳دی","INSAT-3D","weather","isro","INSAT-3D",
 "ماهوارهٔ هواشناسی هند با صوت‌سنج جو و سامانهٔ جست‌وجو و نجات.",
 "India's weather satellite with an atmospheric sounder and search-and-rescue relay."),
(43823,"جئو-کومپ‌ست-۲اِی","GEO-KOMPSAT-2A","weather","kari","GEO-KOMPSAT-2A",
 "ماهوارهٔ هواشناسی زمین‌ثابت کرهٔ جنوبی.",
 "South Korea's geostationary meteorological satellite."),

# ---------------- ناوبری ----------------
(46826,"ناوستار-۸۰ (جی‌پی‌اس نسل سوم)","Navstar 80 (GPS III)","nav","ussf","GPS Block III",
 "از تازه‌ترین ماهواره‌های سامانهٔ موقعیت‌یاب جهانی با سیگنال غیرنظامی ال‌۱سی.",
 "Among the newest GPS spacecraft, broadcasting the civil L1C signal."),
(45854,"ناوستار-۷۹","Navstar 79","nav","ussf","GPS Block III",
 "ماهوارهٔ جی‌پی‌اس در مدار میانی با دقت زمانی اتمی.",
 "A GPS spacecraft in medium orbit with atomic timing accuracy."),
(37846,"گالیله (نمونهٔ نخست پروازی)","Galileo PFM","nav","esa","Galileo (satellite navigation)",
 "نخستین ماهوارهٔ عملیاتی سامانهٔ ناوبری اروپا.",
 "First operational spacecraft of Europe's navigation system."),
(38857,"گالیله اف‌ام۳","Galileo FM3","nav","esa","Galileo (satellite navigation)",
 "بخشی از منظومهٔ اروپایی با دقت غیرنظامی زیرمتری.",
 "Part of Europe's constellation offering sub-metre civil accuracy."),
(40315,"گلوناس-کا","GLONASS-K","nav","roscosmos","GLONASS-K",
 "نسل تازهٔ سامانهٔ ناوبری روسیه با عمر و دقت بیشتر.",
 "New generation of Russia's navigation system with longer life and better accuracy."),
(32275,"گلوناس-اِم","GLONASS-M","nav","roscosmos","GLONASS",
 "ستون فقرات کنونی منظومهٔ ناوبری روسیه در مدار میانی.",
 "Backbone of Russia's current navigation constellation in medium orbit."),
(43001,"بی‌دو-۳ اِم۱","BeiDou-3 M1","nav","cnsa","BeiDou",
 "ماهوارهٔ مدار میانی سامانهٔ جهانی ناوبری چین.",
 "Medium-orbit spacecraft of China's global navigation system."),
(36828,"بی‌دو-۲ آی‌جی‌اس‌او-۱","BeiDou-2 IGSO-1","nav","cnsa","BeiDou",
 "ماهوارهٔ زمین‌همنوای مایل که پوشش منطقه‌ای آسیا را تقویت می‌کند.",
 "Inclined geosynchronous satellite strengthening regional coverage over Asia."),
(39199,"آی‌آر‌ان‌اس‌اس-۱اِی","IRNSS-1A","nav","isro","Indian Regional Navigation Satellite System",
 "نخستین ماهوارهٔ سامانهٔ ناوبری منطقه‌ای هند (ناوایک).",
 "First satellite of India's regional navigation system, NavIC."),
(56759,"ان‌وی‌اس-۰۱","NVS-01","nav","isro","Indian Regional Navigation Satellite System",
 "نسل دوم ناوایک با ساعت اتمی ساخت هند.",
 "Second-generation NavIC with an Indian-built atomic clock."),
(49336,"کیو‌زد‌اس-۱آر میچیبیکی","QZS-1R (Michibiki)","nav","jaxa","Quasi-Zenith Satellite System",
 "ماهوارهٔ شبه‌سرسویی ژاپن که دقت جی‌پی‌اس را در دره‌های شهری بالا می‌برد.",
 "Japan's quasi-zenith satellite boosting GPS accuracy in urban canyons."),
(42738,"کیو‌زد‌اس-۲ میچیبیکی","QZS-2 (Michibiki-2)","nav","jaxa","Quasi-Zenith Satellite System",
 "در مداری مایل و کشیده، ساعت‌ها بر فراز ژاپن می‌ماند.",
 "In an inclined elliptical orbit, lingering for hours above Japan."),

# ---------------- مخابرات زمین‌ثابت ----------------
(26900,"اینتل‌ست ۹۰۲","Intelsat 902","comm","intelsat","Intelsat",
 "ماهوارهٔ کهنه‌کار مخابراتی برای پیوند قاره‌ها بر فراز اقیانوس اطلس.",
 "Veteran communications satellite linking continents over the Atlantic."),
(33459,"یوتل‌ست هات‌برد ۱۳سی","Eutelsat Hotbird 13C","comm","eutelsat","Hot Bird",
 "از موقعیت ۱۳ درجهٔ شرقی صدها شبکهٔ تلویزیونی اروپا و خاورمیانه را پخش می‌کند.",
 "Broadcasts hundreds of European and Middle Eastern TV channels from 13°E."),
(29055,"آسترا ۱کی‌آر","Astra 1KR","comm","ses","Astra 1KR",
 "ماهوارهٔ پخش مستقیم تلویزیونی اروپا در موقعیت ۱۹٫۲ درجهٔ شرقی.",
 "Direct-to-home broadcasting satellite for Europe at 19.2°E."),
(36516,"اس‌ای‌اس-۱","SES-1","comm","ses","SES-1",
 "ماهوارهٔ پخش و ارتباطات برای قارهٔ آمریکا.",
 "Broadcast and data satellite serving the Americas."),
(39476,"اینمارست ۵-اف۱","Inmarsat 5-F1","comm","inmarsat","Inmarsat-5",
 "بخشی از شبکهٔ جهانی اکسپرس برای ارتباط پهن‌باند کشتی و هواپیما.",
 "Part of the Global Xpress network for maritime and airborne broadband."),
(56370,"وایاست-۳ اف۱","ViaSat-3 F1","comm","viasat","ViaSat-3",
 "از پرظرفیت‌ترین ماهواره‌های اینترنتی زمین‌ثابت جهان.",
 "Among the highest-capacity broadband satellites ever launched."),
(57479,"جوپیتر-۳","Jupiter-3 (EchoStar 24)","comm","echostar","Jupiter-3",
 "بزرگ‌ترین ماهوارهٔ مخابراتی تجاری ساخته‌شده با جرمی نزدیک به ۹ تن.",
 "The largest commercial communications satellite built, close to nine tonnes."),
(39022,"یامال-۴۰۲","Yamal-402","comm","gazprom","Yamal (satellite)",
 "ماهوارهٔ مخابراتی روسیه برای پوشش سیبری و اروپا.",
 "Russian communications satellite covering Siberia and Europe."),
(39487,"اکسپرس-اِی‌ام۵","Express-AM5","comm","rscc","Ekspress-AM5",
 "ماهوارهٔ پرظرفیت دولتی روسیه بر فراز خاور دور.",
 "High-capacity Russian state satellite over the Far East."),
(42662,"چاینا‌ست-۱۶","ChinaSat 16","comm","cgwic","Chinasat",
 "نخستین ماهوارهٔ پرظرفیت چین با پیوند نوری آزمایشی.",
 "China's first high-throughput satellite, with an experimental laser link."),
(52817,"نایل‌ست-۳۰۱","Nilesat-301","comm","nilesat","Nilesat",
 "ماهوارهٔ پخش مصر برای شمال آفریقا و خاورمیانه.",
 "Egypt's broadcasting satellite for North Africa and the Middle East."),
(36745,"عرب‌ست-۵اِی","Arabsat-5A","comm","arabsat","Arabsat",
 "ماهوارهٔ سازمان مخابراتی کشورهای عربی.",
 "Satellite of the Arab Satellite Communications Organization."),
(41029,"بدر-۷","Badr-7","comm","arabsat","Arabsat",
 "ماهوارهٔ پخش تلویزیونی خاورمیانه و آفریقا در موقعیت ۲۶ درجهٔ شرقی.",
 "Television broadcast satellite for the Middle East and Africa at 26°E."),
(47306,"ترک‌ست-۵اِی","Türksat 5A","comm","turksat","Türksat 5A",
 "ماهوارهٔ مخابراتی ترکیه برای پوشش اروپا، خاورمیانه و آفریقا.",
 "Turkey's communications satellite covering Europe, the Middle East and Africa."),
(50212,"ترک‌ست-۵بی","Türksat 5B","comm","turksat","Türksat 5B",
 "ماهوارهٔ پرظرفیت ترکیه با تمرکز بر خدمات پهن‌باند.",
 "Turkey's high-throughput satellite focused on broadband services."),
(37265,"کره‌ست-۶","Koreasat 6","comm","ktsat","Koreasat",
 "ماهوارهٔ پخش و ارتباطات کرهٔ جنوبی.",
 "South Korea's broadcast and communications satellite."),
(27831,"اپتوس سی۱","Optus C1","comm","optus","Optus C1",
 "ماهوارهٔ دوکاربرهٔ غیرنظامی و دفاعی استرالیا.",
 "Australia's dual civil and defence communications satellite."),
(35755,"جی‌سی‌ست-۱۲","JCSAT-12","comm","skyperfect","JSAT Corporation",
 "ماهوارهٔ مخابراتی ژاپن برای آسیا و اقیانوسیه.",
 "Japanese communications satellite for Asia and Oceania."),
(52904,"می‌ست ۳دی","MEASAT-3d","comm","measat","MEASAT",
 "ماهوارهٔ پرظرفیت مالزی برای اینترنت روستایی.",
 "Malaysia's high-throughput satellite bringing rural broadband."),
(41552,"تای‌کام-۸","Thaicom 8","comm","thaicom","Thaicom",
 "ماهوارهٔ پخش تایلند برای جنوب شرقی آسیا.",
 "Thailand's broadcasting satellite for Southeast Asia."),
(43228,"هیسپاست ۳۰دبلیو-۶","Hispasat 30W-6","comm","hispasat","Hispasat",
 "ماهوارهٔ اسپانیا برای پوشش اروپا و آمریکای لاتین.",
 "Spain's satellite covering Europe and Latin America."),
(40733,"استار وان سی۴","Star One C4","comm","embratel","Star One",
 "ماهوارهٔ برزیلی برای پخش تلویزیونی آمریکای جنوبی.",
 "Brazilian satellite for South American television."),
(43700,"اِس‌هیل-۲","Es'hail-2","comm","eshailsat","Es'hail 2",
 "ماهوارهٔ قطر که نخستین بازپخش‌گر رادیو آماتوری زمین‌ثابت جهان را نیز حمل می‌کند.",
 "Qatar's satellite, also carrying the world's first geostationary amateur-radio transponder."),
(62483,"ثریا-۴","Thuraya-4","comm","yahsat","Thuraya",
 "ماهوارهٔ تلفن همراه ماهواره‌ای امارات با پوشش خاورمیانه، آفریقا و آسیا.",
 "UAE mobile-satellite spacecraft covering the Middle East, Africa and Asia."),
(37393,"یاه‌ست ۱اِی","Yahsat 1A","comm","yahsat","Yahsat",
 "ماهوارهٔ مخابراتی امارات با کاربرد دوگانه.",
 "UAE dual-use communications satellite."),
(39079,"آذرفضا-۱","Azerspace-1","comm","azercosmos","Azerspace-1",
 "نخستین ماهوارهٔ مخابراتی جمهوری آذربایجان.",
 "Azerbaijan's first communications satellite."),
(39728,"قزاق‌ست-۳","KazSat-3","comm","kazcosmos","KazSat",
 "ماهوارهٔ مخابراتی قزاقستان برای آسیای مرکزی.",
 "Kazakhstan's communications satellite for Central Asia."),
(54033,"آنگوست-۲","AngoSat-2","comm","angosat","AngoSat",
 "ماهوارهٔ آنگولا که پس از شکست ماهوارهٔ نخست جایگزین آن شد.",
 "Angola's replacement satellite after the failure of its first spacecraft."),
(38014,"نایج‌کام‌ست ۱آر","NigComSat-1R","comm","nigcomsat","NigComSat-1R",
 "ماهوارهٔ مخابراتی نیجریه برای غرب آفریقا.",
 "Nigeria's communications satellite for West Africa."),
(43463,"بنگابندو-۱","Bangabandhu-1","comm","bsccl","Bangabandhu-1",
 "نخستین ماهوارهٔ بنگلادش برای پخش و ارتباطات.",
 "Bangladesh's first satellite for broadcasting and communications."),
(59915,"پاک‌ست-اِم‌اِم۱","PakSat-MM1","comm","suparco","Paksat-MM1",
 "ماهوارهٔ چندمنظورهٔ پاکستان برای اینترنت و پخش.",
 "Pakistan's multi-mission satellite for internet and broadcasting."),
(28945,"اسپین‌ست","SpainSat","comm","hisdesat","Spainsat",
 "ماهوارهٔ ارتباطات امن دولت اسپانیا.",
 "Secure communications satellite of the Spanish government."),
(67757,"جام‌جم-۱","Jam-e Jam 1","comm","iran","Jam-e Jam 1",
 "نخستین ماهوارهٔ مخابراتی زمین‌ثابت ایران که پخش تلویزیونی و ارتباطات را بر عهده دارد.",
 "Iran's first geostationary communications satellite, for broadcasting and telecom."),

# ---------------- مخابرات مدار پایین و میانی ----------------
(41917,"ایریدیوم ۱۰۶","Iridium 106","comm","iridium","Iridium satellite constellation",
 "از منظومهٔ ۶۶ ماهواره‌ای که پوشش تلفن ماهواره‌ای را در سراسر کرهٔ زمین فراهم می‌کند.",
 "Part of the 66-satellite constellation giving pole-to-pole satellite telephony."),
(31573,"گلوبال‌استار اِم۰۶۹","Globalstar M069","comm","globalstar","Globalstar",
 "منظومهٔ تلفن و پیام ماهواره‌ای در مدار پایین.",
 "Low-orbit constellation for satellite telephony and messaging."),
(25118,"اورب‌کام اف‌اِم۰۶","Orbcomm FM06","iot","orbcomm","Orbcomm",
 "از نخستین شبکه‌های پیام‌رسانی ماشین‌به‌ماشین در مدار.",
 "One of the first machine-to-machine messaging networks in orbit."),
(39188,"او۳بی اف‌اِم۵","O3b FM5","comm","ses","O3b",
 "منظومهٔ مدار میانی برای اینترنت کم‌تأخیر در نواحی دورافتاده.",
 "Medium-orbit constellation delivering low-latency internet to remote regions."),
(44057,"وان‌وب-۰۰۱۲","OneWeb-0012","mega","oneweb","OneWeb",
 "نمونه‌ای از منظومهٔ پهن‌باند وان‌وب در مدار قطبی.",
 "A sample of the OneWeb broadband constellation in polar orbit."),
(44714,"استارلینک-۱۰۰۸","Starlink-1008","mega","spacex","Starlink",
 "نمونه‌ای از بزرگ‌ترین منظومهٔ تاریخ با هزاران ماهوارهٔ اینترنتی.",
 "A sample of the largest constellation ever flown, with thousands of internet satellites."),
(42837,"لِمور-۲","Lemur-2","iot","spire","Spire Global",
 "ماهوارهٔ مکعبی که هم پیام کشتی‌ها را می‌گیرد و هم جو زمین را با روش پنهان‌سازی رهگیری می‌کند.",
 "CubeSat that both tracks ship signals and sounds the atmosphere by radio occultation."),
(44314,"تیان‌چی-۳","Tianqi-3","iot","guodian","Tianqi",
 "منظومهٔ اینترنت اشیای چین برای مناطق بدون پوشش زمینی.",
 "China's internet-of-things constellation for areas without ground coverage."),

# ---------------- دفاعی و هشدار زودهنگام ----------------
(37481,"اس‌بی‌آی‌آر‌اس جئو-۱","SBIRS GEO-1","defense","ussf","Space-Based Infrared System",
 "سامانهٔ فروسرخ هشدار زودهنگام پرتاب موشک از مدار زمین‌ثابت.",
 "Infrared early-warning system detecting missile launches from geostationary orbit."),
(36868,"اِی‌ای‌اچ‌اف-۱","AEHF-1","defense","ussf","Advanced Extremely High Frequency",
 "ماهوارهٔ ارتباطات راهبردی مقاوم در برابر اختلال.",
 "Jam-resistant strategic communications satellite."),
(34713,"دبلیو‌جی‌اس اف۲","WGS F2","defense","ussf","Wideband Global SATCOM",
 "ستون ارتباطات پهن‌باند نظامی آمریکا و شرکای آن.",
 "Backbone of wideband military communications for the US and partners."),
(40296,"مریدیان-۷","Meridian 7","defense","roscosmos","Meridian (satellite)",
 "ماهوارهٔ ارتباطی روسیه در مدار بیضوی مولنیا برای پوشش قطب شمال.",
 "Russian communications satellite in a Molniya orbit covering the high Arctic."),
(58582,"یائوگان-۴۱","Yaogan-41","defense","cnsa","Yaogan",
 "ماهوارهٔ سنجش از دور بزرگ چین در مدار زمین‌ثابت.",
 "Large Chinese remote-sensing satellite in geostationary orbit."),

# ---------------- فناوری و آزمایشی ----------------
(49330,"شی‌جیان-۲۱","Shijian-21","tech","cnsa","Shijian",
 "ماهوارهٔ آزمایشی چین که یک ماهوارهٔ ازکارافتاده را به مدار گورستان برد.",
 "Chinese technology satellite that towed a defunct spacecraft to a graveyard orbit."),
(44910,"شی‌جیان-۲۰","Shijian-20","tech","cnsa","Shijian",
 "سکوی آزمایشی سنگین چین برای نسل تازهٔ ماهواره‌های مخابراتی.",
 "China's heavy technology testbed for a new generation of communications satellites."),
(41838,"شی‌جیان-۱۷","Shijian-17","tech","cnsa","Shijian",
 "آزمایش پیشران الکتریکی و بازرسی مداری.",
 "Testing electric propulsion and orbital inspection."),

# ---------------- ماهواره‌های ایران ----------------
(28893,"سینا-۱","Sina-1","eo","iran","Sina-1",
 "نخستین ماهوارهٔ ایران که در سال ۱۳۸۴ با همکاری روسیه به مدار رفت.",
 "Iran's first satellite, launched in 2005 with Russian cooperation."),
(53370,"خیام","Khayyam","eo","iran","Khayyam (satellite)",
 "ماهوارهٔ سنجش از دور ایران با بالاترین تفکیک مکانی در میان ماهواره‌های این کشور؛ برای پایش کشاورزی، منابع آب و مرزها به کار می‌رود.",
 "Iran's highest-resolution remote-sensing satellite, used for agriculture, water and border monitoring."),
(58817,"ثریا","Soraya","tech","iran","Soraya (satellite)",
 "نخستین ماهواره‌ای که سازمان فضایی ایران با پرتابگر قائم-۱۰۰ به مدار ۷۵۰ کیلومتری رساند.",
 "The first Iranian satellite placed in a 750-kilometre orbit by the Qaem-100 launcher."),
(59065,"پارس-۱","Pars-1","eo","iran","Pars 1",
 "ماهوارهٔ سنجش از دور ایران با سه دوربین چندطیفی برای پایش منابع طبیعی.",
 "Iranian remote-sensing satellite with three multispectral cameras for natural resources."),
(61072,"چمران-۱","Chamran-1","tech","iran","Chamran-1",
 "ماهوارهٔ آزمایشی ایران برای سنجش فناوری مانور مداری با پیشران سرد.",
 "Iranian technology satellite testing orbital manoeuvring with a cold-gas thruster."),

# ---------------- افزوده: تنوع کاربردی و مداری ----------------
(58584,"آرکتیکا-ام ۲","Arktika-M 2","weather","roscosmos","Arktika-M",
 "ماهوارهٔ هواشناسی روسیه در مدار بیضوی مولنیا که قطب شمال را پیوسته می‌پاید؛ ناحیه‌ای که ماهواره‌های زمین‌ثابت آن را نمی‌بینند.",
 "Russian weather satellite in a Molniya orbit continuously watching the Arctic, which geostationary satellites cannot see."),
(7530,"اسکار-۷","OSCAR 7 (AO-7)","amateur","amsat","OSCAR 7",
 "کهن‌سال‌ترین ماهوارهٔ فعال جهان؛ در ۱۹۷۴ پرتاب شد، خاموش گشت و پس از بیست سال دوباره به کار افتاد.",
 "The oldest still-working satellite: launched in 1974, it fell silent and revived twenty years later."),
(26958,"پروبا-۱","PROBA-1","tech","esa","PROBA-1",
 "ماهوارهٔ کوچک آزمایشی اروپا که با خودگردانی بالا بیش از دو دهه کار کرده است.",
 "ESA's small autonomous technology satellite, working for over two decades."),
(36037,"پروبا-۲","PROBA-2","science","esa","PROBA-2",
 "پایش تاج خورشید و پلاسمای پیرامون زمین با بارهای آزمایشی نو.",
 "Watches the solar corona and near-Earth plasma with novel payloads."),
(44874,"کئوپس","CHEOPS","science","esa","CHEOPS",
 "تلسکوپ اروپایی که اندازهٔ سیارات فراخورشیدی شناخته‌شده را دقیق می‌سنجد.",
 "European telescope precisely measuring the size of known exoplanets."),
(63182,"اسفیرکس","SPHEREx","science","nasa","SPHEREx",
 "نقشه‌بردار طیفی تمام‌آسمان برای مطالعهٔ آغاز کیهان و یخ‌های آلی.",
 "All-sky spectral survey studying cosmic origins and interstellar ices."),
(63178,"پانچ","PUNCH","science","nasa","PUNCH (spacecraft)",
 "چهار ماهوارهٔ کوچک که گذار تاج خورشید به باد خورشیدی را تصویربرداری می‌کنند.",
 "Four small satellites imaging how the solar corona becomes the solar wind."),
(40930,"آستروست","AstroSat","science","isro","AstroSat",
 "نخستین رصدخانهٔ چندموجی هند برای رصد همزمان در نور مرئی، فرابنفش و پرتو ایکس.",
 "India's first multi-wavelength observatory, viewing in visible, ultraviolet and X-rays."),
(59908,"ارث‌کر","EarthCARE","earthsci","esa","EarthCARE",
 "مأموریت مشترک اروپا و ژاپن برای سنجش نقش ابر و هواویز در تعادل انرژی زمین.",
 "Europe–Japan mission measuring how clouds and aerosols affect Earth's energy balance."),
(63772,"بایوماس","Biomass","earthsci","esa","Biomass (satellite)",
 "نخستین رادار باند پی فضایی که زیست‌تودهٔ جنگل‌های جهان را اندازه می‌گیرد.",
 "The first spaceborne P-band radar, weighing the world's forest biomass."),
(64899,"میکروکارب","MicroCarb","earthsci","cnes","MicroCarb",
 "ماهوارهٔ کوچک فرانسوی برای نقشه‌برداری منابع و چاهک‌های کربن.",
 "French microsatellite mapping carbon sources and sinks."),
(46278,"جی‌اچ‌جی‌ست-سی۱","GHGSat-C1","earthsci","ghgsat","GHGSat",
 "ماهوارهٔ تجاری که نشت متان از تأسیسات صنعتی را نقطه‌به‌نقطه ردیابی می‌کند.",
 "Commercial satellite pinpointing methane leaks from individual facilities."),
(40069,"متئور-ام ۲","Meteor-M 2","weather","roscosmos","Meteor-M",
 "ماهوارهٔ هواشناسی قطبی روسیه با فرستندهٔ تصویر آنالوگ برای ایستگاه‌های خانگی.",
 "Russian polar weather satellite, also transmitting imagery receivable by hobbyists."),
(42825,"کانوپوس-وی-ای‌کا","Kanopus-V-IK","eo","roscosmos","Kanopus-V",
 "ماهوارهٔ روسی پایش بلایای طبیعی با دوربین فروسرخ ویژهٔ کشف آتش‌سوزی.",
 "Russian disaster-monitoring satellite with an infrared fire-detection camera."),
(44047,"مصرست-اِی","EgyptSat-A","eo","egsa","EgyptSat-A",
 "ماهوارهٔ سنجش از دور مصر برای کشاورزی و برنامه‌ریزی شهری.",
 "Egypt's remote-sensing satellite for agriculture and urban planning."),
(42920,"فورموست-۵","FORMOSAT-5","eo","tasa","FORMOSAT-5",
 "نخستین ماهوارهٔ کاملاً بومی تایوان با حسگر تصویربرداری ساخت داخل.",
 "Taiwan's first fully indigenous satellite with a home-built imaging sensor."),
(44343,"فورموست-۷","FORMOSAT-7","earthsci","tasa","FORMOSAT-7",
 "منظومهٔ مشترک تایوان و آمریکا که با رهگیری سیگنال ناوبری، جو را نیم‌رخ‌گیری می‌کند.",
 "Taiwan–US constellation profiling the atmosphere by tracking navigation signals."),
(44703,"گائوفن-۷","Gaofen-7","eo","cnsa","Gaofen",
 "ماهوارهٔ نقشه‌برداری سه‌بعدی چین با ارتفاع‌سنج لیزری.",
 "China's stereo-mapping satellite carrying a laser altimeter."),
(40961,"جیلین-۱","Jilin-1","eo","changuang","Jilin-1",
 "نخستین ماهوارهٔ تجاری چین برای تصویربرداری و ویدئوی زمین.",
 "China's first commercial imaging and video satellite."),
(52320,"سوپرویو نئو-۱","SuperView Neo-1","eo","cgsti","SuperView",
 "تصویربردار تجاری چین با تفکیک نیم‌متری.",
 "Chinese commercial imager at half-metre resolution."),
(58297,"آمبرا-۰۷","Umbra-07","sar","umbra","Umbra (company)",
 "رادار تجاری بسیار کوچک با تفکیک ۲۵ سانتی‌متر.",
 "Very small commercial radar reaching 25-centimetre resolution."),
(52184,"نوست-۲۶","NuSat-26","eo","satellogic","Satellogic",
 "منظومهٔ تصویربرداری آرژانتینی با هدف نقشه‌برداری روزانهٔ کرهٔ زمین.",
 "Argentine imaging constellation aiming to remap the planet daily."),
(56310,"تلئوس-۲","TeLEOS-2","sar","dsta","TeLEOS-2",
 "ماهوارهٔ راداری سنگاپور در مداری استوایی، ویژهٔ پایش دریایی مناطق گرمسیری.",
 "Singapore's radar satellite in an equatorial orbit for tropical maritime surveillance."),
(39078,"آمازوناس-۳","Amazonas 3","comm","hispasat","Amazonas (satellite)",
 "ماهوارهٔ مخابراتی اسپانیا برای پوشش آمریکای لاتین.",
 "Spanish communications satellite covering Latin America."),
(38734,"گونتس-اِم ۳","Gonets-M 3","iot","roscosmos","Gonets",
 "منظومهٔ پیام‌رسانی روسیه برای مناطق دورافتادهٔ سیبری و قطب.",
 "Russian store-and-forward messaging constellation for Siberia and the Arctic."),
(43180,"کانوپوس-وی ۳","Kanopus-V 3","eo","roscosmos","Kanopus-V",
 "بخشی از منظومهٔ رصد زمین روسیه با تفکیک ۲٫۱ متر.",
 "Part of Russia's Earth-observation constellation at 2.1 metres."),
(44207,"تیان‌هوی ۲-۰۱اِی","Tianhui 2-01A","sar","cnsa","Tianhui",
 "زوج راداری چین برای تولید مدل ارتفاعی رقومی.",
 "Chinese radar pair generating digital elevation models."),
(47231,"گائوفن-۱۴","Gaofen-14","eo","cnsa","Gaofen",
 "ماهوارهٔ نقشه‌برداری دقیق چین برای تهیهٔ نقشه‌های مقیاس بزرگ.",
 "Chinese precision mapping satellite for large-scale cartography."),
(39159,"پروبا-وی","PROBA-V","eo","esa","PROBA-V",
 "پایش روزانهٔ پوشش گیاهی جهان با دوربین دیدگسترده.",
 "Daily global vegetation monitoring with a wide-field camera."),
(31113,"های‌یانگ-۱بی","Haiyang-1B","earthsci","cnsa","Haiyang",
 "ماهوارهٔ اقیانوس‌شناسی چین برای پایش دما و رنگ آب.",
 "Chinese ocean satellite monitoring water temperature and colour."),
(37781,"های‌یانگ-۲اِی","Haiyang-2A","earthsci","cnsa","Haiyang-2A",
 "ارتفاع‌سنج راداری چین برای سنجش موج و باد سطح دریا.",
 "China's radar altimeter measuring sea waves and surface wind."),
(29045,"جی‌سی‌ست-۵اِی","JCSAT-5A","comm","skyperfect","JSAT Corporation",
 "ماهوارهٔ مخابراتی ژاپن برای خدمات داده و پخش در آسیا.",
 "Japanese satellite providing data and broadcast services across Asia."),
(41752,"اینست-۳دی‌آر","INSAT-3DR","weather","isro","INSAT-3DR",
 "ماهوارهٔ هواشناسی و امداد هند در مدار زمین‌ثابت.",
 "India's geostationary meteorology and disaster-relief satellite."),
(45246,"جئو-کومپ‌ست-۲بی","GEO-KOMPSAT-2B","earthsci","kari","GEO-KOMPSAT-2B",
 "نخستین ماهوارهٔ زمین‌ثابت جهان با سنجندهٔ اختصاصی آلودگی هوا.",
 "The world's first geostationary satellite dedicated to air-quality monitoring."),
(40367,"فنگ‌یون-۲جی","Fengyun-2G","weather","cma","Fengyun",
 "نسل نخست ماهواره‌های زمین‌ثابت هواشناسی چین.",
 "First generation of China's geostationary weather satellites."),
(43437,"سنتینل-۳بی","Sentinel-3B","earthsci","esa","Sentinel-3",
 "همزاد سنتینل-۳اِی برای پایش روزانهٔ اقیانوس و خشکی.",
 "Twin of Sentinel-3A giving daily ocean and land coverage."),
(60989,"سنتینل-۲سی","Sentinel-2C","eo","esa","Sentinel-2",
 "تازه‌ترین تصویربردار نوری برنامهٔ کوپرنیک.",
 "Newest optical imager of the Copernicus programme."),
(66315,"سنتینل-۱دی","Sentinel-1D","sar","esa","Sentinel-1",
 "تازه‌ترین رادار کوپرنیک که پوشش دوماهواره‌ای اروپا را کامل می‌کند.",
 "Newest Copernicus radar, completing Europe's two-satellite coverage."),
(48618,"اس‌بی‌آی‌آر‌اس جئو-۵","SBIRS GEO-5","defense","ussf","Space-Based Infrared System",
 "نسل تازهٔ سکوی هشدار زودهنگام آمریکا بر پایهٔ اتوبوس ال‌ام۲۱۰۰.",
 "Newer US early-warning platform built on the LM2100 bus."),
(44453,"مریدیان-۸","Meridian 8","defense","roscosmos","Meridian (satellite)",
 "ماهوارهٔ ارتباطی بیضوی روسیه برای ناوگان قطبی.",
 "Russian elliptical-orbit communications satellite for the polar fleet."),
(30797,"تمیس-دی","THEMIS D","science","nasa","THEMIS",
 "یکی دیگر از کاوشگرهای تمیس در مدار بیضوی بلند.",
 "Another THEMIS probe in a long elliptical orbit."),
(40483,"ام‌ام‌اس-۲","MMS 2","science","nasa","Magnetospheric Multiscale Mission",
 "دومین فضاپیمای منظومهٔ چهارگانهٔ ام‌ام‌اس.",
 "Second spacecraft of the four-satellite MMS formation."),
(31574,"گلوبال‌استار اِم۰۷۲","Globalstar M072","comm","globalstar","Globalstar",
 "نمونهٔ دیگری از منظومهٔ تلفن ماهواره‌ای گلوبال‌استار.",
 "Another spacecraft of the Globalstar telephony constellation."),
(39189,"او۳بی اف‌اِم۴","O3b FM4","comm","ses","O3b",
 "ماهوارهٔ مدار میانی استوایی برای اینترنت جزایر و کشتی‌ها.",
 "Equatorial medium-orbit satellite serving islands and ships."),
(67264,"کوثر ۱٫۵","Kowsar 1.5","eo","iran","Kowsar (satellite)",
 "ماهوارهٔ تصویربرداری بخش خصوصی ایران با تفکیک زیرمتری.",
 "Privately built Iranian imaging satellite with sub-metre resolution."),
]

def main():
    d = json.load(open("data/sats.json", encoding="utf-8"))
    I = {k: i for i, k in enumerate(d["fields"])}
    have = {s[I["id"]]: s[I["name"]] for s in d["sats"]}
    out, missing = {}, []
    for (i, fa, en, use, op, wiki, fad, end) in T:
        if i not in have:
            missing.append((i, en)); continue
        out[str(i)] = {"fa": fa, "en": en, "use": use, "op": op, "wiki": wiki,
                       "fa_d": fad, "en_d": end, "raw": have[i]}
    json.dump(out, open("data/sat_featured.json", "w", encoding="utf-8"),
              ensure_ascii=False, separators=(",", ":"))
    print("نوشته شد:", len(out), "ماهواره")
    if missing:
        print("یافت نشد:", missing)

if __name__ == "__main__":
    main()
